-- Locus schema — HUMAN-REFERENCE SNAPSHOT of the current DB state.
--
-- This file is authoritative for *documentation* of the schema.
-- It is NOT applied directly. The operational source of truth is the Alembic migration set
-- in db/migrations/versions/, applied via `alembic upgrade head` (or locus.db.migrate.migrate).
-- When you add a migration, update this snapshot to match the resulting state.
--
-- Current state == migrations applied through revision: 0004
--   0001 initial schema
--   0002 chunks_fts (FTS5 lexical index over chunk text + sync triggers) for hybrid retrieval
--   0003 temporal + category metadata: documents.source_date (ISO 'YYYY-MM-DD') + category,
--        each indexed, for --since/--until/--category retrieval facets [re-ingest-bound]
--   0004 widened documents.source_type CHECK to
--        ('pdf','code','video','docx','markdown','text','notebook') for step-8 format
--        breadth (table rebuild — SQLite cannot ALTER a CHECK)
--
-- Version tracking is owned by Alembic's `alembic_version` table.
--
-- For the full table DDL, see db/migrations/versions/0001_init.py.
