-- Locus schema — HUMAN-REFERENCE SNAPSHOT of the current DB state.
--
-- This file is authoritative for *documentation* of the schema.
-- It is NOT applied directly. The operational source of truth is the Alembic migration set
-- in db/migrations/versions/, applied via `alembic upgrade head` (or locus.db.migrate.migrate).
-- When you add a migration, update this snapshot to match the resulting state.
--
-- Current state == migrations applied through revision: 0008
--   0001 initial schema
--   0002 chunks_fts (FTS5 lexical index over chunk text + sync triggers) for hybrid retrieval
--   0003 temporal + category metadata: documents.source_date (ISO 'YYYY-MM-DD') + category,
--        each indexed, for --since/--until/--category retrieval facets [re-ingest-bound]
--   0004 widened documents.source_type CHECK to
--        ('pdf','code','video','docx','markdown','text','notebook') for step-8 format
--        breadth (table rebuild — SQLite cannot ALTER a CHECK)
--   0005 pass_cache(key PK, payload, created_at): content-keyed LLM pass-output cache so
--        commit-triggered repo re-ingests only re-run passes on changed files (step 10)
--   0006 widened documents.source_type CHECK again, adding 'slides' for the step-9 .pptx
--        extractor (same table-rebuild pattern as 0004)
--   0007 figures(id, section_id NULLABLE, doc_id, position, page, kind raster|vector|slide,
--        caption, description, raw_path, embed_model, UNIQUE(doc_id, position)) +
--        figure_vectors vec0 — figures as a first-class retrieval unit (step 11, §15.1);
--        image PNGs live in the flat raw store as '{content_hash}_fig{N}.png'
--   0008 entity_aliases(id, variant_name, variant_type, canonical_name, canonical_type,
--        cluster_id, tier identity|casefold|punct|acronym|plural|llm,
--        UNIQUE(variant_name, variant_type)) + variant/canonical indexes — cross-document
--        alias canonicalization (step 12, §15.4). DERIVED + REGENERABLE: built by
--        `locus link`, rebuild = delete + recompute; `entities` is never mutated.
--        Total mapping (singletons get canonical = self) so consumers inner-join.
--
-- Version tracking is owned by Alembic's `alembic_version` table.
--
-- For the full table DDL, see db/migrations/versions/0001_init.py.
